### ISSUE TITLE
vs code reports an error

### ISSUE THREAD

**Issue by mindmind** [beyonk-adventures/sapper-rbac#8]
Hello!
I can not start the dev environment, catch the error:

svana.webapp git:(auth-system) ✗ yarn run dev
yarn run v1.22.4
warning package.json: No license field
$ sapper dev
server (1.0s)
client (1.2s)
/Users/mindmind/Projects/svana/svana.webapp/node_modules/@beyonk/sapper-rbac/index.js:1
import guard from './lib/guard.js'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/mindmind/Projects/svana/svana.webapp/__sapper__/dev/server/server.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Server crashed
service worker (17ms)

also vs code shows error:
![image](https://user-images.githubusercontent.com/3200435/94711363-b4c4de80-0350-11eb-81eb-970c5d14b31a.png)

**Comment by mindmind** [comment]
also:
![image](https://user-images.githubusercontent.com/3200435/94712208-d4103b80-0351-11eb-891d-8bb907dc5b4d.png)

**Comment by mindmind** [comment]
Sorry, I reinstalled the package with the --dev flag and it worked
